### ISSUE TITLE
Auto-upgrade bug?

### ISSUE THREAD

**Issue by yujh-yujh** [lvandeve/etherealfarm#3]
I don’t know if anyone can notice this, since discord is blocked here, so anyways:
Auto-upgrade doesn’t work when you’re away.
I’ve uploaded an image here as a prove of this: [https://ibb.co/sPSrmmH](url)

(When is the squirrel update?)

**Comment by lvandeve** [comment]
In the screenshot, it looks like some berries are upgraded, mushrooms and flowers are not. What automaton options do you have available? Is auto upgrade enabled, and automaton enabled? What % resource setting have you configured in automaton, and do you have the different settings for different crops unlocked, if so what % resources have you set individually for berry, flower, mushroom, and so on?

Squirrel update soon!

**Comment by yujh-yujh** [comment]
I’ve saw it upgrading grape as soon as I was back after ~ 2 mins
I’m 100% berry 2% mush and flower
It seems to be fixed though, I’m not quite sure.
~3 mis later: no, still not quite working, and I’m using the newest version v0.1.73, iPad, SAFARI.
I’m quite sure that it’s enabled

**Comment by yujh-yujh** [comment]
Ok I know. It’s when I’m busy with other tabs in the browser, so when I’m back there isn’t anything shown like ‘large time delta’, so I guess that when I close the browser it will be fully functioning. (Tested once)

[off-topic]ok, but does currant secret exist in lv5?[/off-topic]

**Comment by yujh-yujh** [comment]
Tested again, still not working(tested up to lingonberry which took me ~20 mins) I’ve tested with the browsers closed) still 100% for upgrades)

also, why is the X so big?

**Comment by lvandeve** [comment]
Sorry for the late response, I'm not sure if this is still an issue now (since the code has changed significantly and many bugs fixed over time), so will close it now.
