### ISSUE TITLE
Bonus fruit storage slots for having seen 2-seasonal/star fruits.

### ISSUE THREAD

**Issue by Al-Lexx** [lvandeve/etherealfarm#7]
Prior to v0.1.100 max value of seen_seasonal_fruit was 15.
So, in order to get bonus slots for having seen all 2-seasonal fruits/star fruit in v0.1.100 the player has to fuse them again.

Is it possible to check fruit collection and update seen_seasonal_fruit based on fruits present?
That way players will get bonus slot for star fruit at least.

**Comment by lvandeve** [comment]
Thanks for the suggestion. However, since it's still possible to gain the extra slot by fusing new fruits, it was not worth it to add code to support the special case for existing savegames. The extra slots are a reward for fusing from now on, not for fuses that were done before the update
