### ISSUE TITLE
I can’t read Roman numerals

### ISSUE THREAD

**Issue by TheGamer1002** [lvandeve/etherealfarm#9]
Hi there! Could you please add an option to replace Roman numerals with standard, Arabic numbers (1, 2, 3…)? It’s tough to discern what the difference between XIV and XVI is. Thanks!

**Comment by lvandeve** [comment]
Good idea, done. You can find the new setting under the number format settings.

It'll still display roman numbers op to 12 (XII) for style reasons, the ones used on clocks and pretty readable. After that it'll use decimal
